 
[![Typing SVG](https://readme-typing-svg.herokuapp.com?font=Fira+Code&weight=500&size=16&duration=4500&pause=2000&color=00FF9C&center=true&vCenter=true&width=700&lines=%E2%9A%A1+%22Don't+just+learn+the+tools+%E2%80%94+build+things+that+matter%22;%F0%9F%9A%80+Turning+data+into+decisions+%7C+Automating+the+boring+stuff)](https://github.com/mahipalrajpurohit529-dotcom)
 
[![Footer](https://capsule-render.vercel.app/api?type=waving&color=0:0a0a0a,50:003322,100:00ff9c&height=140&section=footer&animation=fadeIn)](https://github.com/mahipalrajpurohit529-dotcom)
 
</div>
